name: Integration

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  Integration-tests:
    name: Integrating codes from development to staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
